pub mod common;

use dev_cleaner::classify::{Ecosystem, Lockfile, lockfile_for, lockfile_kinds, parse_lockfile};
use std::path::Path;

/// npm 7 and later. Every install path is a key under `packages`.
const NPM_V3: &str = r#"{
  "name": "app",
  "lockfileVersion": 3,
  "packages": {
    "": { "name": "app", "version": "1.0.0" },
    "packages/ui": { "version": "0.0.0" },
    "node_modules/left-pad": { "version": "1.3.0", "resolved": "https://x/left-pad.tgz" },
    "node_modules/react": { "version": "18.3.1" },
    "node_modules/react/node_modules/scheduler": { "version": "0.23.0" }
  }
}"#;

/// npm 7 writing for older clients: `packages` and the legacy tree together.
const NPM_V2: &str = r#"{
  "lockfileVersion": 2,
  "packages": {
    "": { "version": "1.0.0" },
    "node_modules/left-pad": { "version": "1.3.0" }
  },
  "dependencies": {
    "left-pad": { "version": "1.3.0" }
  }
}"#;

/// npm 6. Only the nested tree exists.
const NPM_V1: &str = r#"{
  "lockfileVersion": 1,
  "dependencies": {
    "left-pad": { "version": "1.3.0" },
    "react": {
      "version": "18.3.1",
      "dependencies": { "scheduler": { "version": "0.23.0" } }
    }
  }
}"#;

const PNPM: &str = r#"lockfileVersion: '9.0'

importers:

  .:
    dependencies:
      react:
        specifier: ^18.3.1
        version: 18.3.1

packages:

  '@babel/code-frame@7.29.7':
    resolution: {integrity: sha512-aaa==}
    engines: {node: '>=6.9.0'}

  react-dom@18.3.1(react@18.3.1):
    resolution: {integrity: sha512-bbb==}

  /legacy-pkg/1.0.0:
    resolution: {integrity: sha512-ccc==}

snapshots:

  '@babel/code-frame@7.29.7':
    dependencies: {}
"#;

const YARN_V1: &str = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.10.4":
  version "7.24.7"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.24.7.tgz"
  integrity sha512-aaa==

left-pad@^1.3.0:
  version "1.3.0"
  resolved "https://registry.yarnpkg.com/left-pad/-/left-pad-1.3.0.tgz"
"#;

const YARN_BERRY: &str = r#"# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
  cacheKey: 10c0

"@babel/code-frame@npm:^7.0.0":
  version: 7.24.7
  resolution: "@babel/code-frame@npm:7.24.7"
  checksum: 10c0/aaa
"#;

const CARGO: &str = r#"version = 3

[[package]]
name = "clap"
version = "4.6.6"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "dev-cleaner"
version = "0.1.0"
dependencies = ["clap"]
"#;

const POETRY: &str = r#"[[package]]
name = "certifi"
version = "2024.2.2"
description = "Python package for providing Mozilla's CA Bundle."
optional = false
python-versions = ">=3.6"
files = [
    {file = "certifi-2024.2.2-py3-none-any.whl", hash = "sha256:aaa"},
]
"#;

const UV: &str = r#"version = 1
requires-python = "==3.12.*"

[[package]]
name = "aiohappyeyeballs"
version = "2.7.1"
source = { registry = "https://pypi.org/simple" }
sdist = { url = "https://x/aiohappyeyeballs-2.7.1.tar.gz", hash = "sha256:aaa", size = 24757 }
wheels = [
    { url = "https://x/aiohappyeyeballs-2.7.1-py3-none-any.whl", hash = "sha256:bbb", size = 15038 },
]

[[package]]
name = "wheel-only"
version = "1.0.0"
source = { registry = "https://pypi.org/simple" }
wheels = [
    { url = "https://x/wheel_only-1.0.0-py3-none-any.whl", hash = "sha256:ccc", size = 99 },
]
"#;

const GEMFILE: &str = r#"GEM
  remote: https://rubygems.org/
  specs:
    activesupport (7.2.2.1)
      base64
      i18n (>= 1.6, < 2)
    addressable (2.8.7)
      public_suffix (>= 2.0.2, < 7.0)

PLATFORMS
  arm64-darwin-24

DEPENDENCIES
  activesupport

BUNDLED WITH
   2.5.9
"#;

/// Every format, paired with the name it is stored under. The whole corpus.
fn corpus() -> Vec<(&'static str, &'static str)> {
    vec![
        ("package-lock.json", NPM_V3),
        ("pnpm-lock.yaml", PNPM),
        ("yarn.lock", YARN_V1),
        ("Cargo.lock", CARGO),
        ("Gemfile.lock", GEMFILE),
        ("poetry.lock", POETRY),
        ("uv.lock", UV),
    ]
}

fn parse(name: &str, text: &str) -> Lockfile {
    parse_lockfile(&Path::new("/p").join(name), text)
        .unwrap_or_else(|err| panic!("{name} should parse: {err}"))
}

fn names(lock: &Lockfile) -> Vec<&str> {
    lock.packages.iter().map(|p| p.name.as_str()).collect()
}

fn version_of<'a>(lock: &'a Lockfile, name: &str) -> &'a str {
    lock.packages
        .iter()
        .find(|p| p.name == name)
        .unwrap_or_else(|| panic!("{name} missing from {:?}", names(lock)))
        .version
        .as_str()
}

#[test]
fn every_lockfile_name_maps_to_the_toolchain_that_wrote_it() {
    for (name, eco) in [
        ("package-lock.json", Ecosystem::Node),
        ("pnpm-lock.yaml", Ecosystem::Node),
        ("yarn.lock", Ecosystem::Node),
        ("Cargo.lock", Ecosystem::Rust),
        ("Gemfile.lock", Ecosystem::Ruby),
        ("poetry.lock", Ecosystem::Python),
        ("uv.lock", Ecosystem::Python),
    ] {
        let kind = lockfile_for(name).unwrap_or_else(|| panic!("{name} should be recognised"));
        assert_eq!(
            kind.ecosystem, eco,
            "{name} attributed to the wrong toolchain"
        );
    }
    assert_eq!(lockfile_kinds().len(), 7, "registry size changed");
}

#[test]
fn files_that_are_not_lockfiles_are_not_claimed() {
    // A manifest is not a lockfile: package.json names ranges, not resolutions.
    for name in ["package.json", "Cargo.toml", "Gemfile", "", "yarn.lock.bak"] {
        assert!(lockfile_for(name).is_none(), "{name} must not be claimed");
    }
}

#[test]
fn npm_v3_reads_every_installed_path_and_nothing_else() {
    let lock = parse("package-lock.json", NPM_V3);
    // "" is the project itself and "packages/ui" is a workspace member: neither
    // is an installed dependency, and both would be counted as one.
    assert_eq!(names(&lock), ["left-pad", "react", "scheduler"]);
    assert_eq!(version_of(&lock, "scheduler"), "0.23.0");
}

#[test]
fn npm_v2_does_not_count_the_legacy_tree_twice() {
    // Version 2 carries `packages` and `dependencies` describing the same
    // install. Reading both reports one dependency as two.
    let lock = parse("package-lock.json", NPM_V2);
    assert_eq!(names(&lock), ["left-pad"]);
}

#[test]
fn npm_v1_reads_the_nested_dependency_tree() {
    let lock = parse("package-lock.json", NPM_V1);
    assert_eq!(names(&lock), ["left-pad", "react", "scheduler"]);
}

#[test]
fn pnpm_keys_split_into_name_and_version_across_layouts() {
    let lock = parse("pnpm-lock.yaml", PNPM);
    assert_eq!(
        names(&lock),
        ["@babel/code-frame", "legacy-pkg", "react-dom"],
        "the importers block and the snapshots block are not package lists"
    );
    // The scope's @ is not the version separator, and a peer suffix is not part
    // of the version.
    assert_eq!(version_of(&lock, "@babel/code-frame"), "7.29.7");
    assert_eq!(version_of(&lock, "react-dom"), "18.3.1");
    // pnpm 5 wrote /name/version instead.
    assert_eq!(version_of(&lock, "legacy-pkg"), "1.0.0");
}

#[test]
fn yarn_v1_pairs_each_header_with_the_version_below_it() {
    let lock = parse("yarn.lock", YARN_V1);
    assert_eq!(names(&lock), ["@babel/code-frame", "left-pad"]);
    assert_eq!(version_of(&lock, "@babel/code-frame"), "7.24.7");
}

#[test]
fn yarn_berry_parses_and_its_metadata_block_is_not_a_package() {
    let lock = parse("yarn.lock", YARN_BERRY);
    assert_eq!(names(&lock), ["@babel/code-frame"]);
    assert_eq!(version_of(&lock, "@babel/code-frame"), "7.24.7");
}

#[test]
fn cargo_lock_lists_its_packages_and_records_no_size() {
    let lock = parse("Cargo.lock", CARGO);
    assert_eq!(names(&lock), ["clap", "dev-cleaner"]);
    assert!(
        lock.packages.iter().all(|p| p.bytes.is_none()),
        "cargo records no size, and Some(0) would claim it records zero"
    );
}

#[test]
fn poetry_lock_lists_its_packages() {
    let lock = parse("poetry.lock", POETRY);
    assert_eq!(names(&lock), ["certifi"]);
    assert_eq!(version_of(&lock, "certifi"), "2024.2.2");
}

#[test]
fn uv_lock_carries_the_size_it_records_and_none_where_it_does_not() {
    let lock = parse("uv.lock", UV);
    let sized = &lock.packages[0];
    assert_eq!(sized.name, "aiohappyeyeballs");
    assert_eq!(sized.bytes, Some(24_757));
    let unsized_pkg = &lock.packages[1];
    assert_eq!(unsized_pkg.name, "wheel-only");
    assert_eq!(
        unsized_pkg.bytes, None,
        "a wheel-only package has no source distribution to size"
    );
}

#[test]
fn gemfile_lock_reads_the_specs_not_their_dependencies() {
    let lock = parse("Gemfile.lock", GEMFILE);
    // `base64` and `i18n` sit one level deeper as requirements of a gem, and
    // the DEPENDENCIES block names ranges rather than resolved versions.
    assert_eq!(names(&lock), ["activesupport", "addressable"]);
    assert_eq!(version_of(&lock, "activesupport"), "7.2.2.1");
}

#[test]
fn a_package_named_at_several_paths_is_counted_once() {
    let text = r#"{
      "lockfileVersion": 3,
      "packages": {
        "node_modules/left-pad": { "version": "1.3.0" },
        "node_modules/a/node_modules/left-pad": { "version": "1.3.0" },
        "node_modules/b/node_modules/left-pad": { "version": "1.1.0" }
      }
    }"#;
    let lock = parse("package-lock.json", text);
    assert_eq!(names(&lock), ["left-pad", "left-pad"]);
    let versions: Vec<&str> = lock.packages.iter().map(|p| p.version.as_str()).collect();
    assert_eq!(
        versions,
        ["1.1.0", "1.3.0"],
        "distinct versions stay distinct"
    );
}

/// A lockfile cut off mid-write is the failure this has to survive. A scan that
/// dies on one bad file is worse than a scan that steps over it.
#[test]
fn a_truncated_lockfile_degrades_to_a_warning_in_every_format() {
    for (name, full_text) in corpus() {
        let full = parse(name, full_text);
        assert!(!full.packages.is_empty(), "{name} fixture parsed nothing");

        let cut = &full_text[..full_text.len() / 2];
        match parse_lockfile(&Path::new("/p").join(name), cut) {
            Ok(partial) => assert!(
                partial.packages.len() <= full.packages.len(),
                "{name}: truncation invented packages"
            ),
            Err(warning) => assert!(
                warning.contains(name),
                "{name}: the warning must name the file it came from, got {warning:?}"
            ),
        }
    }
}

#[test]
fn garbage_in_place_of_a_lockfile_degrades_to_a_warning() {
    for (name, _) in corpus() {
        let path = Path::new("/p").join(name);
        // Not a panic and not a claim of packages that are not there.
        let packages = parse_lockfile(&path, "\u{0}\u{1}not a lockfile {[\"")
            .map(|l| l.packages.len())
            .unwrap_or(0);
        assert_eq!(packages, 0, "{name} claimed packages from garbage");
    }
}

mod walk {
    use super::common::Fixture;
    use dev_cleaner::classify::lockfiles_in;
    use dev_cleaner::scan::Walker;

    fn found(fx: &Fixture) -> (Vec<dev_cleaner::classify::Lockfile>, Vec<String>) {
        lockfiles_in(&Walker::new([fx.root()]).walk().files)
    }

    #[test]
    fn a_lockfile_inside_an_artifact_directory_belongs_to_a_dependency() {
        let fx = Fixture::new();
        fx.file("app/package-lock.json", super::NPM_V3.as_bytes());
        // Dependencies ship their own lockfiles. Reading them reports one
        // project's install as hundreds of projects, the same way an
        // unfiltered walk inflated project detection.
        fx.file(
            "app/node_modules/dep/package-lock.json",
            super::NPM_V3.as_bytes(),
        );
        fx.file("app/target/vendored/Cargo.lock", super::CARGO.as_bytes());

        let (locks, warnings) = found(&fx);
        assert_eq!(locks.len(), 1, "found {:?}", locks.iter().map(|l| &l.path));
        assert!(locks[0].path.ends_with("app/package-lock.json"));
        assert!(warnings.is_empty(), "{warnings:?}");
    }

    #[test]
    fn a_lockfile_that_will_not_parse_costs_a_warning_not_the_walk() {
        let fx = Fixture::new();
        fx.file("good/Cargo.lock", super::CARGO.as_bytes());
        fx.file("bad/Cargo.lock", b"[[package");

        let (locks, warnings) = found(&fx);
        assert_eq!(locks.len(), 1, "the readable lockfile still came back");
        assert_eq!(warnings.len(), 1, "got {warnings:?}");
        assert!(
            warnings[0].contains("bad/Cargo.lock"),
            "the warning must name the file: {:?}",
            warnings[0]
        );
    }
}
